/**
 * WCAG Success Criteria identifiers (scId) keyed by Success Criterion number
 * (e.g. "1.1.1"). Used by the EARL reporter to map axe-core "wcagNNN" rule tags
 * to WCAG SC identifiers for the EARL report's isPartOf field.
 *
 * Derived from dequelabs/act-reports-axe (src/axe-reporter-earl/wcag.json),
 * reduced to the scId field the reporter consumes. Covers WCAG 2.1 and earlier;
 * WCAG 2.2 success criteria are not included.
 *
 * @see https://www.w3.org/TR/WCAG21/
 */
const wcagData = {
  '1.1.1': 'WCAG2:non-text-content',
  '1.2.1': 'WCAG2:audio-only-and-video-only-prerecorded',
  '1.2.2': 'WCAG2:captions-prerecorded',
  '1.2.3': 'WCAG2:audio-description-or-media-alternative-prerecorded',
  '1.2.4': 'WCAG2:captions-live',
  '1.2.5': 'WCAG2:audio-description-prerecorded',
  '1.2.6': 'WCAG2:sign-language-prerecorded',
  '1.2.7': 'WCAG2:extended-audio-description-prerecorded',
  '1.2.8': 'WCAG2:media-alternative-prerecorded',
  '1.2.9': 'WCAG2:audio-only-live',
  '1.3.1': 'WCAG2:info-and-relationships',
  '1.3.2': 'WCAG2:meaningful-sequence',
  '1.3.3': 'WCAG2:sensory-characteristics',
  '1.3.4': 'WCAG2:orientation',
  '1.3.5': 'WCAG2:identify-input-purpose',
  '1.3.6': 'WCAG2:identify-purpose',
  '1.4.1': 'WCAG2:use-of-color',
  '1.4.2': 'WCAG2:audio-control',
  '1.4.3': 'WCAG2:contrast-minimum',
  '1.4.4': 'WCAG2:resize-text',
  '1.4.5': 'WCAG2:images-of-text',
  '1.4.6': 'WCAG2:contrast-enhanced',
  '1.4.7': 'WCAG2:low-or-no-background-audio',
  '1.4.8': 'WCAG2:visual-presentation',
  '1.4.9': 'WCAG2:images-of-text-no-exception',
  '1.4.10': 'WCAG2:reflow',
  '1.4.11': 'WCAG2:non-text-contrast',
  '1.4.12': 'WCAG2:text-spacing',
  '1.4.13': 'WCAG2:content-on-hover-or-focus',
  '2.1.1': 'WCAG2:keyboard',
  '2.1.2': 'WCAG2:no-keyboard-trap',
  '2.1.3': 'WCAG2:keyboard-no-exception',
  '2.1.4': 'WCAG2:character-key-shortcuts',
  '2.2.1': 'WCAG2:timing-adjustable',
  '2.2.2': 'WCAG2:pause-stop-hide',
  '2.2.3': 'WCAG2:no-timing',
  '2.2.4': 'WCAG2:interruptions',
  '2.2.5': 'WCAG2:re-authenticating',
  '2.2.6': 'WCAG2:timeouts',
  '2.3.1': 'WCAG2:three-flashes-or-below-threshold',
  '2.3.2': 'WCAG2:three-flashes',
  '2.3.3': 'WCAG2:animation-from-interactions',
  '2.4.1': 'WCAG2:bypass-blocks',
  '2.4.2': 'WCAG2:page-titled',
  '2.4.3': 'WCAG2:focus-order',
  '2.4.4': 'WCAG2:link-purpose-in-context',
  '2.4.5': 'WCAG2:multiple-ways',
  '2.4.6': 'WCAG2:headings-and-labels',
  '2.4.7': 'WCAG2:focus-visible',
  '2.4.8': 'WCAG2:location',
  '2.4.9': 'WCAG2:link-purpose-link-only',
  '2.4.10': 'WCAG2:section-headings',
  '2.5.1': 'WCAG2:pointer-gestures',
  '2.5.2': 'WCAG2:pointer-cancellation',
  '2.5.3': 'WCAG2:label-in-name',
  '2.5.4': 'WCAG2:motion-actuation',
  '2.5.5': 'WCAG2:target-size',
  '2.5.6': 'WCAG2:concurrent-input-mechanisms',
  '3.1.1': 'WCAG2:language-of-page',
  '3.1.2': 'WCAG2:language-of-parts',
  '3.1.3': 'WCAG2:unusual-words',
  '3.1.4': 'WCAG2:abbreviations',
  '3.1.5': 'WCAG2:reading-level',
  '3.1.6': 'WCAG2:pronunciation',
  '3.2.1': 'WCAG2:on-focus',
  '3.2.2': 'WCAG2:on-input',
  '3.2.3': 'WCAG2:consistent-navigation',
  '3.2.4': 'WCAG2:consistent-identification',
  '3.2.5': 'WCAG2:change-on-request',
  '3.3.1': 'WCAG2:error-identification',
  '3.3.2': 'WCAG2:labels-or-instructions',
  '3.3.3': 'WCAG2:error-suggestion',
  '3.3.4': 'WCAG2:error-prevention-legal-financial-data',
  '3.3.5': 'WCAG2:help',
  '3.3.6': 'WCAG2:error-prevention-all',
  '4.1.1': 'WCAG2:parsing',
  '4.1.2': 'WCAG2:name-role-value',
  '4.1.3': 'WCAG2:status-messages'
};

export default wcagData;
