# Do not rename this file. The name "deploy.yml" is known to
# NPM for trusted OIDC publishing.
name: Deploy

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - master
      - develop

concurrency:
  group: deploy/${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy-next:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    environment:
      name: registry.npmjs.org
    permissions:
      contents: read
      # Required for OIDC
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - &install-deps
        name: Install Dependencies
        uses: ./.github/actions/install-deps
      - &build
        name: Build
        run: |
          npm run prepare
          npm run build
      - &validate-package
        name: Validate package is consumable
        env:
          # Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#runner-context
          # Linting shows this context might be invalid, but it shouldn't be per docs.
          # Probably something missing in the schema.
          DEBUG: ${{ runner.debug == '1' }}
        run: node .github/bin/validate-package.mjs
      - name: Publish "next" version to NPM
        run: npm publish --tag=next
  prod-hold:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    environment:
      name: production-hold
    runs-on: ubuntu-24.04
    steps:
      - name: Awaiting approval to deploy to production
        run: echo "Approval granted to proceed to production deployment."
  prod-deploy:
    needs: prod-hold
    if: ${{ needs.prod-hold.result == 'success' }}
    environment:
      name: registry.npmjs.org
    permissions:
      contents: read
      # Required for OIDC
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - *checkout
      - *install-deps
      - *build
      - *validate-package
      - name: Publish stable version to NPM
        run: npm publish
