name: Nightly Tests

on:
  schedule:
    # Runs every day at 2:17 AM UTC
    # Schedules should try to be offset from common times
    # to avoid high contention times on GitHub runners.
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nightly-browsers:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    env:
      DISPLAY: ':99'
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Dependencies
        id: install-deps
        uses: ./.github/actions/install-deps
        with:
          nightly: 'true'
          start-xvfb: ${{ env.DISPLAY }}
      - name: Build
        run: |
          npm run prepare
          npm run build
      - name: Run Firefox Nightly Browser Tests
        env:
          FIREFOX_NIGHTLY_BIN: ${{ steps.install-deps.outputs.firefox-path }}
        run: npm run test -- --browsers FirefoxNightly
      - name: Run Chrome Beta Browser Tests
        env:
          CHROME_BIN: ${{ steps.install-deps.outputs.chrome-path }}
          CHROMEDRIVER_BIN: ${{ steps.install-deps.outputs.chromedriver-path }}
          CHROME_DEVEL_SANDBOX: /opt/google/chrome/chrome-sandbox
        run: npm run test -- --browsers Chrome
